// GENERATED by Modules/lua-module/generate-bindings.py - do not edit.
// Source: gpio.signatures

#include "bindings_private.h"

#include <tactility/drivers/gpio_controller.h>
#include <tactility/error.h>

extern "C" {
#include <lauxlib.h>
}

namespace {

static int lua_gpio_descriptor_release(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);

    const error_t error = gpio_descriptor_release(argument0);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, 1);
    return 1;
}

static int lua_gpio_descriptor_get_pin_number(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);
    uint8_t argument1 = (uint8_t)0;

    const error_t error = gpio_descriptor_get_pin_number(argument0, &argument1);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushinteger(state, argument1);
    return 1;
}

static int lua_gpio_descriptor_set_level(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);
    const bool argument1 = lua_toboolean(state, 2) != 0;

    const error_t error = gpio_descriptor_set_level(argument0, argument1);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, 1);
    return 1;
}

static int lua_gpio_descriptor_get_level(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);
    bool argument1 = (bool)0;

    const error_t error = gpio_descriptor_get_level(argument0, &argument1);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, argument1);
    return 1;
}

static int lua_gpio_descriptor_set_flags(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);
    const uint16_t argument1 = (uint16_t)luaL_checkinteger(state, 2);

    const error_t error = gpio_descriptor_set_flags(argument0, argument1);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, 1);
    return 1;
}

static int lua_gpio_descriptor_get_flags(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);
    uint16_t argument1 = (uint16_t)0;

    const error_t error = gpio_descriptor_get_flags(argument0, &argument1);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushinteger(state, argument1);
    return 1;
}

static int lua_gpio_descriptor_has_flags(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);
    const uint16_t argument1 = (uint16_t)luaL_checkinteger(state, 2);
    bool argument2 = (bool)0;

    const error_t error = gpio_descriptor_has_flags(argument0, argument1, &argument2);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, argument2);
    return 1;
}

static int lua_gpio_descriptor_enable_interrupt(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);

    const error_t error = gpio_descriptor_enable_interrupt(argument0);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, 1);
    return 1;
}

static int lua_gpio_descriptor_disable_interrupt(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);

    const error_t error = gpio_descriptor_disable_interrupt(argument0);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, 1);
    return 1;
}

static int lua_gpio_descriptor_remove_callback(lua_State* state) {
    auto* argument0 = lua_bindings_check_gpio_descriptor(state, 1);

    const error_t error = gpio_descriptor_remove_callback(argument0);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushboolean(state, 1);
    return 1;
}

static int lua_gpio_controller_get_pin_count(lua_State* state) {
    auto* argument0 = lua_bindings_check_device(state, 1);
    uint32_t argument1 = (uint32_t)0;

    const error_t error = gpio_controller_get_pin_count(argument0, &argument1);
    if (error != ERROR_NONE) {
        lua_pushnil(state);
        lua_pushstring(state, error_to_string(error));
        return 2;
    }

    lua_pushinteger(state, argument1);
    return 1;
}

const luaL_Reg functions[] = {
    { "descriptor_release", lua_gpio_descriptor_release },
    { "descriptor_get_pin_number", lua_gpio_descriptor_get_pin_number },
    { "descriptor_set_level", lua_gpio_descriptor_set_level },
    { "descriptor_get_level", lua_gpio_descriptor_get_level },
    { "descriptor_set_flags", lua_gpio_descriptor_set_flags },
    { "descriptor_get_flags", lua_gpio_descriptor_get_flags },
    { "descriptor_has_flags", lua_gpio_descriptor_has_flags },
    { "descriptor_enable_interrupt", lua_gpio_descriptor_enable_interrupt },
    { "descriptor_disable_interrupt", lua_gpio_descriptor_disable_interrupt },
    { "descriptor_remove_callback", lua_gpio_descriptor_remove_callback },
    { "controller_get_pin_count", lua_gpio_controller_get_pin_count },
    { nullptr, nullptr }
};

} // namespace

void lua_bindings_open_gpio(lua_State* state) {
    luaL_newlib(state, functions);
    lua_setfield(state, -2, "gpio");
}

