name: Build Firmware
on:
  push:
    branches:
    - test
  pull_request:
    types: [opened, synchronize, reopened]

permissions: read-all

jobs:
  cyd-8048s043c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build"
      uses: ./.github/actions/build-firmware
      with:
        board_id: cyd-8048s043c
        arch: esp32s3
  waveshare-s3-touch-lcd-128:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build"
      uses: ./.github/actions/build-firmware
      with:
        board_id: waveshare-s3-touch-lcd-128
        arch: esp32s3
  waveshare-s3-lcd-13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "Build"
      uses: ./.github/actions/build-firmware
      with:
        board_id: waveshare-s3-lcd-13
        arch: esp32s3
